# (generated with --quick)

import logging
import okra.error_handling
import okra.models
from typing import Any, List, Optional, Tuple, Type, TypeVar

DataAccessLayer: Type[okra.models.DataAccessLayer]
DirectoryNotCreatedError: Type[okra.error_handling.DirectoryNotCreatedError]
MissingEnvironmentVariableError: Type[okra.error_handling.MissingEnvironmentVariableError]
NetworkError: Type[okra.error_handling.NetworkError]
logger: logging.Logger
logging: module
os: module
shutil: module

AnyStr = TypeVar('AnyStr', str, bytes)

def clone_repo(repo_name: str, dirpath: str) -> bool: ...
def compress_repo(repo_name: str, cache: str, repo_comp: str) -> bool: ...
def create_parent_dir(repo_name: str, dirpath: str) -> bool: ...
def decompress_repo(repo_comp: str, cache) -> bool: ...
def gcloud_analysis() -> None: ...
def gcloud_clone_or_fetch_repo(repo_name: str) -> bool: ...
def gcloud_persistance(repo_name: str) -> None: ...
def get_truck_factor_by_project(owner, project, dal) -> Tuple[Any, Any]: ...
def local_persistance(repo_name: str, parent_dir: str, buffer_size = ...) -> None: ...
def perform_truck_analysis() -> None: ...
def persist_repo_data(dirpath, urlstring) -> None: ...
def populate_db(dburl: str, cache: str, repo_name: str, buffer_size = ...) -> None: ...
def read_gcloud_blob(bucket_id: str, gpath: str, fpath: str) -> bool: ...
def retrieve_or_clone(repo_name: str, dirpath: str) -> bool: ...
def simple_version_truck_factor(repos: list, dirpath: str, dburl: str, b: int) -> List[Tuple[Any, Any]]: ...
def update_repo(repo_name: str, dirpath: str) -> bool: ...
def urljoin(base: AnyStr, url: Optional[AnyStr], allow_fragments: bool = ...) -> AnyStr: ...
def write_gcloud_blob(bucket_id: str, gpath: str, fpath: str) -> None: ...
