# (generated with --quick)

import collections
import okra.models
from typing import Any, List, Tuple, Type

Author: Type[okra.models.Author]
CommitFile: Type[okra.models.CommitFile]
Contrib: Type[okra.models.Contrib]
Info: Type[okra.models.Info]
Meta: Type[okra.models.Meta]
defaultdict: Type[collections.defaultdict]
func: Any

def author_number_of_files_owned(results) -> collections.defaultdict: ...
def file_author_owner(dal, yearmo = ...) -> list: ...
def get_bus_factor(dal, yearmo = ...) -> Tuple[int, List[Tuple[Any, Any]]]: ...
def max_lines_perfile(res) -> list: ...
def number_of_contributors(dal, yearmo = ...) -> Any: ...
def number_of_files(dal, yearmo = ...) -> Any: ...
def smallest_owner_set(authors, total, size = ...) -> Tuple[int, List[Tuple[Any, Any]]]: ...
