# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/okra_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/okra_api.proto',
  package='okra.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15protos/okra_api.proto\x12\x07okra.v1\"3\n\x10RepositoryMetric\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\x02\"4\n\x0b\x43ontributor\x12\x14\n\x0c\x63ontrib_name\x18\x01 \x01(\t\x12\x0f\n\x07repo_id\x18\x02 \x01(\t\"g\n\x0eRepositoryInfo\x12\x0f\n\x07repo_id\x18\x01 \x01(\t\x12\x11\n\trepo_name\x18\x02 \x01(\t\x12\x16\n\x0erepo_namespace\x18\x03 \x01(\t\x12\x19\n\x11\x66irst_commit_date\x18\x04 \x01(\tb\x06proto3')
)




_REPOSITORYMETRIC = _descriptor.Descriptor(
  name='RepositoryMetric',
  full_name='okra.v1.RepositoryMetric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repo_id', full_name='okra.v1.RepositoryMetric.repo_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='okra.v1.RepositoryMetric.rating', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=85,
)


_CONTRIBUTOR = _descriptor.Descriptor(
  name='Contributor',
  full_name='okra.v1.Contributor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contrib_name', full_name='okra.v1.Contributor.contrib_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repo_id', full_name='okra.v1.Contributor.repo_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=139,
)


_REPOSITORYINFO = _descriptor.Descriptor(
  name='RepositoryInfo',
  full_name='okra.v1.RepositoryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repo_id', full_name='okra.v1.RepositoryInfo.repo_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repo_name', full_name='okra.v1.RepositoryInfo.repo_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repo_namespace', full_name='okra.v1.RepositoryInfo.repo_namespace', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_commit_date', full_name='okra.v1.RepositoryInfo.first_commit_date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=244,
)

DESCRIPTOR.message_types_by_name['RepositoryMetric'] = _REPOSITORYMETRIC
DESCRIPTOR.message_types_by_name['Contributor'] = _CONTRIBUTOR
DESCRIPTOR.message_types_by_name['RepositoryInfo'] = _REPOSITORYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RepositoryMetric = _reflection.GeneratedProtocolMessageType('RepositoryMetric', (_message.Message,), dict(
  DESCRIPTOR = _REPOSITORYMETRIC,
  __module__ = 'protos.okra_api_pb2'
  # @@protoc_insertion_point(class_scope:okra.v1.RepositoryMetric)
  ))
_sym_db.RegisterMessage(RepositoryMetric)

Contributor = _reflection.GeneratedProtocolMessageType('Contributor', (_message.Message,), dict(
  DESCRIPTOR = _CONTRIBUTOR,
  __module__ = 'protos.okra_api_pb2'
  # @@protoc_insertion_point(class_scope:okra.v1.Contributor)
  ))
_sym_db.RegisterMessage(Contributor)

RepositoryInfo = _reflection.GeneratedProtocolMessageType('RepositoryInfo', (_message.Message,), dict(
  DESCRIPTOR = _REPOSITORYINFO,
  __module__ = 'protos.okra_api_pb2'
  # @@protoc_insertion_point(class_scope:okra.v1.RepositoryInfo)
  ))
_sym_db.RegisterMessage(RepositoryInfo)


# @@protoc_insertion_point(module_scope)
